### ISSUE TITLE
Error when using 2 dimensions with log transformation

### ISSUE THREAD

**Issue by agouy** [tercen/manual_gating_shiny_operator#8] opened 2022-09-26 12:07 UTC
Error when using 2 dimensions with log transformation, it is stuck at the loading step.
It is working in 1 dimension with log transformation, even with negative values.
Other transformations (asinh, biexponential and logicle) work fine. ( both 1D and 2D).

**Comment by tsmonteiro** [comment] 2022-09-26 14:42
I was able to reproduce this error, though I am not sure what is the best option to fix it. As far as my testing goes, this error occurs because the log transformation is resulting in some NaN values. If the NaN filter is used, there is a differing amount of rows for each channel, resulting in an error. Here are the options:

1) Ask the user to remove the NaN filter when using the log and deal with them in the operator by either replacing them with some value, or removing rows with non-finite values in all channels.

2) Keep the filter and find the missing rowIds by comparing the channels. Then, either remove those rows, or set them to some value.

**Comment by agouy** [comment] 2022-09-27 09:55
@tsmonteiro Let's not expect the user to remove the NaN filter. I would exclude the rows with any missing data and document this behaviour in the README (or, ideally, display a message somewhere in the app mentioning that _n_ rows have been excluded due to missing data.)

**Comment by tsmonteiro** [comment] 2022-10-05 14:37
This is addressed in version 0.5.0

**Closed by tsmonteiro** 2022-10-05 14:37 UTC
